name: Build and Publish workshop image

on:
  push:
    branches: main

jobs:
  publish_workshop_image:
    name: Push workshop image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build workshop image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: silval/jfrog-workshops-environment:${{ github.run_number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
